<?php

namespace App\Models\Budget;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Category extends Model
{
    public $fillable = ['name', 'slug', 'user_id'];

    public static function boot() {
        parent::boot();

        static::addGlobalScope('user', function($query) {
            $query->where('user_id', auth()->id());
        });

        // automatically save user id when creating new transaction
        static::saving(function($category){
            $category->user_id = $category->user_id ?: auth()->id();
            $category->slug = $category->slug ?: Str::slug($category->name);
        });

        static::updating(function($category) {
            $category->slug = Str::slug($category->name);
        });
    }

    public function getRouteKeyName()
    {
//        return parent::getRouteKeyName(); // TODO: Change the autogenerated stub
        return 'slug';
    }

    public function transactions()
    {
        return $this->hasMany(Transaction::class, 'category_id');
    }
}
